FROM navidonskis/nginx-php7.1

ARG DOCUMENTATION_NAME='*.php'
ARG DOCUMENTATION_EXCLUDES=''
ARG DOCUMENTATION_DIR='/var/project'
ARG DOCUMENTATION_THEME='default'
ARG DOCUMENTATION_BUILD_DIR='/var/www'
ARG DOCUMENTATION_CACHE_DIR='/tmp'
ARG DOCUMENTATION_GITHUB=false
ARG DOCUMENTATION_OPENED_LEVEL=2

ENV DOCUMENTATION_NAME=$DOCUMENTATION_NAME
ENV DOCUMENTATION_EXCLUDES=$DOCUMENTATION_EXCLUDES
ENV DOCUMENTATION_DIR=$DOCUMENTATION_DIR
ENV DOCUMENTATION_THEME=$DOCUMENTATION_THEME
ENV DOCUMENTATION_BUILD_DIR=$DOCUMENTATION_BUILD_DIR
ENV DOCUMENTATION_CACHE_DIR=$DOCUMENTATION_CACHE_DIR
ENV DOCUMENTATION_GITHUB=$DOCUMENTATION_GITHUB
ENV DOCUMENTATION_OPENED_LEVEL=$DOCUMENTATION_OPENED_LEVEL

RUN mkdir /sami
RUN mkdir $DOCUMENTATION_DIR

ADD files/sami.config.php /sami/sami.config.php
ADD files/.bash_profile /root/.bash_profile

RUN echo 'source /etc/profile' >> /root/.bashrc
RUN echo 'source /root/.bash_profile' >> /root/.bashrc

RUN cd /sami && curl -O http://get.sensiolabs.org/sami.phar

RUN php /sami/sami.phar update /sami/sami.config.php -v

EXPOSE 80

WORKDIR /var/www
